##############################
# Queuing bowtie2 mapping to all references and historical Acc UW1 and UW3 for inStrain and relative abundance calculations
##############################

executable = /home/GLBRCORG/emcdaniel/EBPR/Flanking/executables/bowtie-historical-mapping.sh

request_cpus = 6
request_memory = 150GB
arguments = $(sample)

output = /home/GLBRCORG/emcdaniel/EBPR/Flanking/outs/$(Cluster)_$(Process)_bowtie_historical_mapping.out
error = /home/GLBRCORG/emcdaniel/EBPR/Flanking/errs/$(Cluster)_$(Process)_bowtie_historical_mapping.err
log = /home/GLBRCORG/emcdaniel/EBPR/Flanking/logs/$(Cluster)_$(Process)_bowtie_historical_mapping.log

queue sample from metadata/metagenomeList.txt