##############################
# Queuing bowtie2 mapping to Accumulibacter references UW1 and UW3 for R1 metagenomes
##############################

executable = /home/GLBRCORG/emcdaniel/EBPR/Flanking/executables/bowtie-accumulibacter-mapping.sh

request_cpus = 6
request_memory = 150GB
arguments = $(sample) $(r1) $(r2)

output = /home/GLBRCORG/emcdaniel/EBPR/Flanking/outs/$(Cluster)_$(Process)_bowtie_mapping.out
error = /home/GLBRCORG/emcdaniel/EBPR/Flanking/errs/$(Cluster)_$(Process)_bowtie_mapping.err
log = /home/GLBRCORG/emcdaniel/EBPR/Flanking/logs/$(Cluster)_$(Process)_bowtie_mapping.log

queue sample,r1,r2 from metadata/flanking-assemblies-queue.txt