##############################
# inStrain quick profiles
##############################

executable = /home/GLBRCORG/emcdaniel/EBPR/Flanking/executables/flanking-inStrain-quick-profiles.sh

request_cpus = 6
request_memory = 150GB
arguments = $(bam)

output = /home/GLBRCORG/emcdaniel/EBPR/Flanking/outs/$(Cluster)_$(Process)_quick_profile.out
error = /home/GLBRCORG/emcdaniel/EBPR/Flanking/errs/$(Cluster)_$(Process)_quick_profile.err
log = /home/GLBRCORG/emcdaniel/EBPR/Flanking/logs/$(Cluster)_$(Process)_quick_profile.log

queue bam from metadata/Flanking-sorted-bams.txt